### ISSUE TITLE
Set initial populations for a subset of ages

### ISSUE THREAD

**Issue by vbartolino** [lentinj/gadget3#1]
Hi, I'm trying to set initial populations only for a subset of the ages in the two gadgetstocks:
- imm.stk I want to omit age0 because it will come with recruitment
- mat.stk I want to remove the last oldest ages

As I understand, the job is done with ```g3a_initialconditions_normalparam```
Can I add the argument ```run_f = ~cur_step == 1 && age %in% 2:8)``` to set the initial population just for the specified ages?

**Comment by lentinj** [comment]
Basically yes, however there isn't a direct translation of ``%in%`` or ``2:8`` so you'd have to do `` run_f = ~cur_step == 1 && age >=2 && age <= 8) ``.

If this comes up regularly then we could add handle ``%in% 2:8`` and do the above easily enough.

I'm currently playing with the ling model and spotting some missing brackets in the initial conditions formulations by the way, I'll push some bugfixes in a bit.

**Comment by vbartolino** [comment]
Thanks!
