### ISSUE TITLE
maturity parameters missing

### ISSUE THREAD

**Issue by vbartolino** [lentinj/gadget3#2]
why the maturity parameters do not appear here?
```tmb_param <- attr(tmb_ling, 'parameter_template')``` at line 121 of setup.R

I also noticed that ```ling_imm_actions``` contains two identical actions ```comment("Move ling_imm to ling_mat")``` but none of the two contains parameters

**Comment by lentinj** [comment]
Ah, because it's broken :) ``g3a_mature_constant`` assumes that alpha is a constant, and it's not here.

Easy enough to sort though, thanks.

**Comment by lentinj** [comment]
Right, should be fixed with https://github.com/lentinj/gadget3/commit/9cca2e8b83c48831fcbacd410c04fd1a43a4d4d1
